# Set the prompt
autoload -Uz promptinit
promptinit
prompt spaceship

if [ -f ~/.config/sops/age/keys.txt ]; then
	export SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt
fi


# TMUX
# User configuration
# Always work in a tmux session if tmux is installed
# https://github.com/chrishunt/dot-files/blob/master/.zshrc
if which tmux 2>&1 >/dev/null; then
  if [ $TERM != "screen-256color" ] && [  $TERM != "screen" ]; then
    tmux -f "$HOME/.config/tmux/tmux.conf" attach -t hack || tmux new -s hack; exit
  fi
fi

kn() {
	if [ "$1" != "" ]; then
		kubectl config set-context --current --namespace=$1
	else
		echo -e "\e[1;31m Error, please provide a valid Namespace\e[0m"
	fi
}

knd() {
	kubectl config set-context --current --namespace=default
}

ku() {
	kubectl config unset current-context
}

# fzf
if [ -n "${commands[fzf-share]}" ]; then
  source "$(fzf-share)/key-bindings.zsh"
  source "$(fzf-share)/completion.zsh"
fi
